[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
DATABASE_TYPE = "supabase"
JWT_SECRET = "a9c17c4d329c3b779e43a490efef420350f09f79cecf22d911357cab306a2c93"
SUPABASE_URL = "https://yrvawzdcnjlnbmamhwsc.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlydmF3emRjbmpsbmJtYW1od3NjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Nzg3MDIxMiwiZXhwIjoyMDczNDQ2MjEyfQ.RvS90UDa0ClWT1DYzVfUcWJU2KEBQY5YoqDogh3GU3o"
